### ISSUE TITLE
mp4info showing KID won't for decrypting

### ISSUE THREAD

**Issue by alitteration** [axiomatic-systems/Bento4#452]
Hello there,

I'm using mp4info trying to decrypt some ATMOS audio. I got the key itself but it still won't decrypt.
I did mp4info --verbose ATMOS.mp4 and the Keyid was all 00000000000000000000000000000000 so I did something like 00000000000000000000000000000000:01782373000000000000000000002222 for example, but that file still won't be decrypted.

Can the shown KID be different or wrong somehow?

Many thanks

**Comment by barbibulle** [comment]
Unfortunately, decrypting by passing the KID is broken. Only decrypting by Track ID works. So in this case, instead of `00000000000000000000000000000000:01782373000000000000000000002222` for the key, you'd pass something like `1:01782373000000000000000000002222` (for track ID 1)

**Comment by barbibulle** [comment]
I have pushed a new build of the tools to the server. Decrypting by KID should work now. Can you try again and let me know if it works for you?

**Comment by alitteration** [comment]
I appreciate your efforts and concern. I did download the source and re-compiled it, then I tried to decrypt it again but I believe It still won't do it probably. 

Here is the ATMOS audio I was trying to decrypt  : [url]http://www.mediafire.com/file/2m6kbgsmz1jd1th/encrypted_atmos.mp4/file[/url] and the key : 0000000003bc98296336202020202020:71782373faa4eeb09a9a8286d38e1151. I changed the KID to match the one I saw using mp4info.

**Comment by barbibulle** [comment]
Looking at the file you're linking to here, the KID is `00000000000000000000000000000000` (use `mp4info --verbose` to see the default KID), not `0000000003bc98296336202020202020`. What command-line options did you use to encrypt it?

**Comment by alitteration** [comment]
I actually acquired the license from some server that I don't have control over how they encrypt contents.
But I would like to point out that the exact same keys are being given out for an ac3 audio, and they decrypt it just fine.
Here an ac3 audio I've been testing on http://www.mediafire.com/file/bwz1opa4wgsqwxm/Encrypted.ac3/file  

Please use the same key I sent but replacing the KID with all zeroes instead.

**Comment by forty875** [comment]
Same problem here with atmos audio track ...
```
ID                          : 1
Format                      : (Encrypted)
Codec ID                    : enca
Duration                    : 1 h 3 min
Sampling rate               : 48.0 kHz
Bit depth                   : 16 bits
Title                       : Core Media Audio
Encryption                  : Encrypted
```
This is what mp4info shows https://pastebin.com/A35QXurj

**Comment by barbibulle** [comment]
@alitteration How do you know that the key is the same as the one for the ac3 audio file? Decrypting the ac3 file you're linking to produces a playable file, but decrypting the atmos file produces an audio file that doesn't play, which leads me to believe that the key is not the right one. Unfortunately there's no easy way to check whether a key is right or not, other than trying to decode the decrypted stream (there's no checksum or equivalent to validate the key). Can you share a link to a non-encrypted atmos file, so that I could check whether encrypting and decryting with a known key produces a playable file?

**Comment by alitteration** [comment]
> @alitteration How do you know that the key is the same as the one for the ac3 audio file? Decrypting the ac3 file you're linking to produces a playable file, but decrypting the atmos file produces an audio file that doesn't play, which leads me to believe that the key is not the right one. Unfortunately there's no easy way to check whether a key is right or not, other than trying to decode the decrypted stream (there's no checksum or equivalent to validate the key). Can you share a link to a non-encrypted atmos file, so that I could check whether encrypting and decryting with a known key produces a playable file?

Of course. That is some non-encrypted atmos audio track : https://www.mediafire.com/file/p9vvq9fmd1mq6ej/atmos.mp4/file

**Comment by barbibulle** [comment]
I looked into this a bit more closely today, and it seems that the encrypted atmos file is not correct. The samples in the fragments refer to sample description index 2, which means the 2nd sample description for the track. The sample description is where the codecs details are, as well as the encryption info. However, the track only has one sample description (as it normal for simple audio tracks), so the decrypter doesn't find any crypto info for the samples (they are associated with a non-existent sample description), and therefore doesn't decrypt anything. Do you know what tool was used to encrypt the audio file? It would seem that that tool produced an incorrect file (unless somehow the author of that tool understands the spec differently, in which case I'd like to discuss that with them).

**Comment by fabrebatalla18** [comment]
Any news?

**Comment by barbibulle** [comment]
There's not much I can do from my end without more info on how the encrypted file was generated. It looks incorrect from my point of view, but I'd love to be proven wrong if someone who knows how it was encrypted and why it has those properties can justify why they thing that's correct. (When encrypting Atoms audio with the Bento4 tools, this problem doesn't happen and the file can be decrypted correctly).

**Comment by X-C0DE** [comment]
Has anyone solved this?
